import { ValidationError } from '@/core/errors/validation-error';

export type TransactionId = string;
export type TransactionKind = 'income' | 'expense' | 'transfer';

export interface TransactionProps {
  id: TransactionId;
  accountId: string;
  categoryId?: string;
  description: string;
  amount: number;
  type: TransactionKind;
  occurredAt: Date;
  /** Set when this transaction was generated by an installment plan (purchase or loan). */
  installmentPlanId?: string;
  /** 1-based position within its plan, e.g. 3 of 12. */
  installmentNumber?: number;
  /** Set when this transaction was auto-generated by a recurring rule. */
  recurringRuleId?: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Any movement of money — an income, an expense, or one leg of a transfer.
 * `amount` is always stored positive; the direction it moves an account's
 * balance is derived from `type` by the application layer, never encoded as
 * a negative number here (per invariant: "o valor de uma transação deve ser
 * maior que zero").
 */
export class Transaction {
  constructor(public readonly props: TransactionProps) {
    if (!props.description.trim()) {
      throw new ValidationError('Transaction description is required.');
    }
    if (!Number.isFinite(props.amount) || props.amount <= 0) {
      throw new ValidationError(
        'Transaction amount must be greater than zero.',
      );
    }
  }

  get id() {
    return this.props.id;
  }

  get accountId() {
    return this.props.accountId;
  }

  get categoryId() {
    return this.props.categoryId;
  }

  get description() {
    return this.props.description;
  }

  get amount() {
    return this.props.amount;
  }

  get type() {
    return this.props.type;
  }

  get occurredAt() {
    return this.props.occurredAt;
  }

  get installmentPlanId() {
    return this.props.installmentPlanId;
  }

  get installmentNumber() {
    return this.props.installmentNumber;
  }

  get recurringRuleId() {
    return this.props.recurringRuleId;
  }

  /**
   * The signed effect this transaction has on its account's balance:
   * income increases it, expense and the "outgoing" leg of a transfer
   * decrease it.
   */
  balanceDelta(
    direction: 'in' | 'out' = this.type === 'expense' ? 'out' : 'in',
  ): number {
    return direction === 'in' ? this.amount : -this.amount;
  }
}
