'use client';

import { useActionState, useState } from 'react';
import { useFormStatus } from 'react-dom';

import {
  type ActionResult,
  updateInstallmentAction,
  updateTransactionAction,
} from '@/app/transactions/actions';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { FIELD_BASE_CLASSES } from '@/shared/constants/field-styles';

const INITIAL_STATE: ActionResult = { success: false };

interface TransactionEditDialogProps {
  id: string;
  description: string;
  amount: number;
  occurredAt: Date;
  categoryId?: string;
  categories: Array<{ id: string; name: string }>;
  /** Set when this row was generated by an installment plan — enables the
   * "apply to future installments" option and switches which use-case the
   * edit goes through. */
  isInstallment: boolean;
}

function toDateInputValue(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/**
 * The one editing surface for both a plain transaction and an installment
 * (see ui-ux.md: "Um modal deve abrir sempre da mesma forma") — the only
 * difference is which server action it posts to and whether the
 * "apply to future installments" checkbox is shown.
 */
export function TransactionEditDialog({
  id,
  description,
  amount,
  occurredAt,
  categoryId,
  categories,
  isInstallment,
}: TransactionEditDialogProps) {
  const [open, setOpen] = useState(false);
  const [state, formAction] = useActionState(
    isInstallment ? updateInstallmentAction : updateTransactionAction,
    INITIAL_STATE,
  );

  if (state.success && open) {
    setOpen(false);
  }

  return (
    <>
      <Button variant="ghost" size="sm" onClick={() => setOpen(true)}>
        Editar
      </Button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogHeader>
          <DialogTitle>Editar transação</DialogTitle>
          <DialogDescription>
            Altere o valor, a data, a descrição ou a categoria.
          </DialogDescription>
        </DialogHeader>

        <form action={formAction} className="space-y-4">
          <input type="hidden" name="id" value={id} />

          {state.error && (
            <Alert variant="error">
              <AlertDescription>{state.error}</AlertDescription>
            </Alert>
          )}

          <div className="space-y-2">
            <label className="text-sm font-medium" htmlFor="edit-description">
              Descrição
            </label>
            <Input
              id="edit-description"
              name="description"
              defaultValue={description}
              required
            />
          </div>

          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            <div className="space-y-2">
              <label className="text-sm font-medium" htmlFor="edit-amount">
                Valor
              </label>
              <Input
                id="edit-amount"
                name="amount"
                type="number"
                step="0.01"
                min="0.01"
                defaultValue={amount}
                required
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium" htmlFor="edit-occurredAt">
                Data
              </label>
              <Input
                id="edit-occurredAt"
                name="occurredAt"
                type="date"
                defaultValue={toDateInputValue(occurredAt)}
                required
              />
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium" htmlFor="edit-categoryId">
              Categoria
            </label>
            <select
              id="edit-categoryId"
              name="categoryId"
              defaultValue={categoryId ?? ''}
              className={FIELD_BASE_CLASSES}
            >
              <option value="">Sem categoria</option>
              {categories.map((category) => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
            </select>
          </div>

          {isInstallment && (
            <label className="flex items-center gap-2 text-sm">
              <input
                type="checkbox"
                name="propagateToFuture"
                className="border-input h-4 w-4 rounded"
              />
              Aplicar o novo valor às próximas parcelas
            </label>
          )}

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => setOpen(false)}
            >
              Cancelar
            </Button>
            <SubmitButton />
          </DialogFooter>
        </form>
      </Dialog>
    </>
  );
}

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending}>
      {pending ? 'Salvando…' : 'Salvar alterações'}
    </Button>
  );
}
